### ISSUE TITLE
Typo in User model 

### ISSUE THREAD

**Issue by ffugly** [Sila-Money/sila-sdk#18]
This one gave me a headache for a few hours.  

in `src/models/user.js` line 26

```js
    this.addresAlias = '';   // missing the second 's' in 'address' 
```

**Comment by chrisbra-riftpay** [comment]
> This one gave me a headache for a few hours.
> 
> in `src/models/user.js` line 26
> 
> ```js
>     this.addresAlias = '';   // missing the second 's' in 'address' 
> ```
I believe they are working on that, we don't implement that field currently as it is not required on sila's side for the model to be complete for i.e register. so we store it on our database in the meantime.

**Comment by chepix10** [comment]
Hi @ffugly and @chrisbra-riftpay.
This will be addressed on our next release. You'll be able to continue using the type parameter and the correct one will take precedence.
