### ISSUE TITLE
Typo in .getNacisCategories()

### ISSUE THREAD

**Issue by ffugly** [Sila-Money/sila-sdk#8]
reference to method `/get_naics_categories` endpoint is misspelled.  

in `index.js` line 556
```js
const getNacisCategories = () => {  
  // NOTE: ^ should be getNaicsCategories
  const body = setHeaders({ header: {} });

  return makeRequest('get_naics_categories', body);
};
```
and again in `index.js` line 728, and `README.md` line 571

**Comment by chepix10** [comment]
Thanks @ffugly. This will be addressed in v0.2.13-rc.
Current 'getNacisCategories' method will be marked as deprecated.
